# Generated by Django 5.0.9 on 2026-03-10 17:09

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Klinik', 'verbose_name_plural': 'Klinikler'},
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_id',
            field=models.CharField(default=tenants.models.generate_clinic_id, max_length=6, unique=True, verbose_name='Klinik ID (6 hane)'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Ödeme Yapıldı'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='plan_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Subdomain (ali-klinik)'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='plan',
            field=models.CharField(choices=[('free', 'Ücretsiz'), ('basic', 'Basic - ₺299/ay'), ('pro', 'Pro - ₺799/ay')], default='free', max_length=20, verbose_name='Paket'),
        ),
    ]
