# Generated by Django 5.0.9 on 2026-03-15 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_clinic_options_clinic_clinic_id_clinic_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='Plan')),
                ('period', models.CharField(choices=[('monthly', 'Aylık'), ('yearly', 'Yıllık')], max_length=10, verbose_name='Periyot')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('cancelled', 'İptal Edilmiş'), ('pending', 'Bekliyor')], default='pending', max_length=20, verbose_name='Durum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen Tutar')),
                ('iyzico_payment_id', models.CharField(blank=True, max_length=100, verbose_name='iyzico Ödeme ID')),
                ('iyzico_conversation_id', models.CharField(blank=True, max_length=100, verbose_name='Conversation ID')),
                ('starts_at', models.DateTimeField(verbose_name='Başlangıç')),
                ('expires_at', models.DateTimeField(verbose_name='Bitiş')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.clinic', verbose_name='Klinik')),
            ],
            options={
                'verbose_name': 'Abonelik',
                'ordering': ['-created_at'],
            },
        ),
    ]
