# Generated by Django 5.0.9 on 2026-03-16 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_login_code_delete_doctorlogincode'),
        ('tenants', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Her Yıl Tekrar')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.clinic')),
            ],
            options={
                'verbose_name': 'Tatil Günü',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('is_open', models.BooleanField(default=True, verbose_name='Açık')),
                ('open_time', models.TimeField(default='09:00', verbose_name='Açılış')),
                ('close_time', models.TimeField(default='18:00', verbose_name='Kapanış')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='tenants.clinic')),
            ],
            options={
                'verbose_name': 'Çalışma Saati',
                'ordering': ['day'],
                'unique_together': {('clinic', 'day')},
            },
        ),
        migrations.CreateModel(
            name='DoctorWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('is_working', models.BooleanField(default=True, verbose_name='Çalışıyor')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Başlangıç')),
                ('end_time', models.TimeField(default='18:00', verbose_name='Bitiş')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doktor Çalışma Saati',
                'ordering': ['day'],
                'unique_together': {('doctor', 'day')},
            },
        ),
    ]
