# Generated by Django 5.0.9 on 2026-03-16 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_clinicholiday_clinicworkinghours_doctorworkinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='about',
            field=models.TextField(blank=True, verbose_name='Hakkında'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='appointment_advance_days',
            field=models.IntegerField(default=60, verbose_name='Kaç Gün Önceden Randevu Alınabilir'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='appointment_duration',
            field=models.IntegerField(default=30, verbose_name='Randevu Süresi (dk)'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='appointment_interval',
            field=models.IntegerField(default=15, verbose_name='Randevu Aralığı (dk)'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='E-posta Bildirimleri'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinics/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='İletişim Telefonu'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='reminder_hours_before',
            field=models.IntegerField(default=24, verbose_name='Hatırlatma (saat önce)'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='SMS Bildirimleri'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='plan',
            field=models.CharField(choices=[('free', 'Ücretsiz'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Paket'),
        ),
        migrations.AlterField(
            model_name='clinicholiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clinicholiday',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicholiday',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clinicworkinghours',
            name='close_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='clinicworkinghours',
            name='day',
            field=models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')]),
        ),
        migrations.AlterField(
            model_name='clinicworkinghours',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clinicworkinghours',
            name='open_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='day',
            field=models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')]),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.clinic'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='iyzico_conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='iyzico_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('monthly', 'Aylık'), ('yearly', 'Yıllık')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='starts_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('cancelled', 'İptal Edilmiş'), ('pending', 'Bekliyor')], default='pending', max_length=20),
        ),
    ]
