# Generated by Django 5.0.9 on 2026-03-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_clinic_about_clinic_appointment_advance_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='appointments_open',
            field=models.BooleanField(default=True, verbose_name='Online Randevu Açık'),
        ),
    ]
