# Generated by Django 5.0.9 on 2026-03-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_clinic_appointments_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='Fatura Adresi'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fatura Şehri'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='billing_country',
            field=models.CharField(blank=True, default='TR', max_length=5, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Posta Kodu'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='saved_card_brand',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kart Markası'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='saved_card_expiry',
            field=models.CharField(blank=True, max_length=7, verbose_name='Son Kullanma'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='saved_card_holder',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kart Sahibi'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='saved_card_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Kart Son 4 Hane'),
        ),
    ]
