# Generated by Django 5.0.9 on 2026-03-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_clinic_billing_address_clinic_billing_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.CharField(max_length=4, verbose_name='Son 4 Hane')),
                ('brand', models.CharField(blank=True, max_length=20, verbose_name='Kart Markası')),
                ('holder', models.CharField(blank=True, max_length=100, verbose_name='Kart Sahibi')),
                ('expiry', models.CharField(blank=True, max_length=7, verbose_name='Son Kullanma')),
                ('billing_address', models.TextField(blank=True, verbose_name='Fatura Adresi')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('billing_zip', models.CharField(blank=True, max_length=20, verbose_name='Posta Kodu')),
                ('billing_country', models.CharField(blank=True, default='TR', max_length=5, verbose_name='Ülke')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif Kart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tenants.clinic')),
            ],
            options={
                'verbose_name': 'Klinik Kartı',
                'ordering': ['-created_at'],
            },
        ),
    ]
