# Generated by Django 5.0.9 on 2026-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_cliniccard'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='E-posta Doğrulandı'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Arama Motorunda Görünsün'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='login_otp',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Giriş OTP'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='login_otp_exp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Son Kullanma'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Telefon Doğrulandı'),
        ),
    ]
