# Generated by Django 5.0.9 on 2026-03-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('date_of_birth', models.DateField(verbose_name='Doğum Tarihi')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('gender', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın'), ('D', 'Diğer')], max_length=1, verbose_name='Cinsiyet')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif')], default='aktif', max_length=10, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Randevu Tarihi')),
                ('procedure', models.CharField(max_length=100, verbose_name='İşlem')),
                ('status', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.clinic', verbose_name='Klinik')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Doktor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Ziyaret Tarihi')),
                ('procedures', models.JSONField(default=list, verbose_name='Yapılan İşlemler')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücret (₺)')),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.clinic', verbose_name='Klinik')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Doktor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Ziyaret',
                'verbose_name_plural': 'Ziyaretler',
                'ordering': ['-date_time'],
            },
        ),
    ]
