# Generated by Django 5.0.9 on 2026-03-11 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_about_doctor_photo_alter_doctor_specialties'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name'], 'verbose_name': 'Hasta', 'verbose_name_plural': 'Hastalar'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date_time'], 'verbose_name': 'Ziyaret'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='clinic',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Alerjiler'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A Rh+'), ('A-', 'A Rh-'), ('B+', 'B Rh+'), ('B-', 'B Rh-'), ('AB+', 'AB Rh+'), ('AB-', 'AB Rh-'), ('0+', '0 Rh+'), ('0-', '0 Rh-'), ('bilinmiyor', 'Bilinmiyor')], default='bilinmiyor', max_length=10, verbose_name='Kan Grubu'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acil Kişi Adı'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Acil Kişi Telefonu'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Yakınlık Derecesi'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sigorta Şirketi'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sigorta No'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_notes',
            field=models.TextField(blank=True, verbose_name='Tıbbi Notlar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='Fotoğraf'),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Ödendi mi?'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın'), ('D', 'Belirtmek İstemiyorum')], default='D', max_length=1, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücret'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patients/files/', verbose_name='Dosya')),
                ('file_type', models.CharField(choices=[('rontgen', 'Röntgen'), ('rapor', 'Rapor'), ('recete', 'Reçete'), ('diger', 'Diğer')], default='diger', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Hasta Dosyası',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField(verbose_name='Diş Numarası')),
                ('status', models.CharField(choices=[('saglikli', 'Sağlıklı'), ('dolgulu', 'Dolgulu'), ('cekimli', 'Çekilmiş'), ('implant', 'İmplant'), ('kanal', 'Kanal Tedavisi'), ('kron', 'Kron'), ('hasarli', 'Hasarlı/Çürük'), ('eksik', 'Eksik (Doğuştan)')], default='saglikli', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Not')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Diş Kaydı',
                'unique_together': {('patient', 'tooth_number')},
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
