# Generated by Django 5.0.9 on 2026-03-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_alter_visit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientToothModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patients/tooth_models/', verbose_name='3D Model Dosyası')),
                ('file_format', models.CharField(choices=[('stl', 'STL'), ('obj', 'OBJ'), ('glb', 'GLB/GLTF')], max_length=10, verbose_name='Format')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_models', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Hasta Diş Modeli',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
