# Generated by Django 5.0.9 on 2026-03-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_about_doctor_photo_alter_doctor_specialties'),
        ('patients', '0003_patienttoothmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Tarih ve Saat')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Süre (dk)')),
                ('procedure', models.CharField(choices=[('muayene', 'Muayene'), ('dolgu', 'Dolgu'), ('cekim', 'Çekim'), ('kanal', 'Kanal Tedavisi'), ('implant', 'İmplant'), ('kron', 'Kron/Köprü'), ('temizlik', 'Diş Temizliği'), ('beyazlatma', 'Beyazlatma'), ('ortodonti', 'Ortodonti'), ('protez', 'Protez'), ('rontgen', 'Röntgen'), ('diger', 'Diğer')], default='muayene', max_length=50, verbose_name='İşlem')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücret')),
                ('status', models.CharField(choices=[('bekliyor', '⏳ Bekliyor'), ('onaylandi', '✅ Onaylandı'), ('tamamlandi', '✔️ Tamamlandı'), ('iptal', '❌ İptal')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctors.doctor', verbose_name='Doktor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Randevu',
                'ordering': ['date_time'],
            },
        ),
    ]
