# Generated by Django 5.0.9 on 2026-03-13 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_appointment'),
        ('tenants', '0002_alter_clinic_options_clinic_clinic_id_clinic_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tenants.clinic', verbose_name='Klinik'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='tenants.clinic', verbose_name='Klinik'),
        ),
        migrations.AddField(
            model_name='visit',
            name='complaint',
            field=models.TextField(blank=True, verbose_name='Şikayet'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('bekliyor', '⏳ Bekliyor'), ('onaylandi', '✅ Onaylandı'), ('tamamlandi', '✔️ Tamamlandı'), ('tamamlanamadi', '❌ Tamamlanamadı'), ('iptal', '🚫 İptal')], default='bekliyor', max_length=20, verbose_name='Durum'),
        ),
    ]
