# Generated by Django 5.0.9 on 2026-03-13 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_photo_appointment_clinic_and_more'),
        ('tenants', '0002_alter_clinic_options_clinic_clinic_id_clinic_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('yeni_randevu', 'Yeni Randevu'), ('iptal_randevu', 'Randevu İptali')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.clinic')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'ordering': ['-created_at'],
            },
        ),
    ]
