# Generated by Django 5.0.9 on 2026-03-16 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HastaOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Hasta OTP',
            },
        ),
        migrations.CreateModel(
            name='HastaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hasta Kullanıcı',
            },
        ),
        migrations.CreateModel(
            name='HastaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hasta_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.hastauser')),
            ],
        ),
    ]
