# Generated by Django 5.0.9 on 2026-03-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_hastaotp_hastauser_hastasession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HastaOTP',
        ),
        migrations.RemoveField(
            model_name='hastauser',
            name='name',
        ),
        migrations.AddField(
            model_name='hastauser',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hastauser',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Soyad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hastauser',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='Şifre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hastauser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-posta'),
        ),
    ]
