# Generated by Django 5.0.9 on 2026-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_delete_hastaotp_remove_hastauser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hastauser',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Kan Grubu'),
        ),
        migrations.AddField(
            model_name='hastauser',
            name='insurance_company',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sigorta Şirketi'),
        ),
        migrations.AddField(
            model_name='hastauser',
            name='insurance_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Sigorta No'),
        ),
    ]
