# Generated by Django 5.0.9 on 2026-03-18 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_hastauser_blood_type_hastauser_insurance_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='İlk Muayene', max_length=100, verbose_name='Etiket')),
                ('snapshot_date', models.DateField(verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_snapshots', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Diş Haritası',
                'ordering': ['snapshot_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='toothrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='toothrecord',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.toothsnapshot'),
        ),
        migrations.AlterUniqueTogether(
            name='toothrecord',
            unique_together={('patient', 'snapshot', 'tooth_number')},
        ),
    ]
