# Generated by Django 5.0.9 on 2026-03-10 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(max_length=20, unique=True, verbose_name='Doktor ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon')),
                ('specialties', models.JSONField(verbose_name='Uzmanlık Alanları')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktorlar',
            },
        ),
    ]
