# Generated by Django 5.0.9 on 2026-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkında'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/photos/', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.JSONField(default=list, verbose_name='Uzmanlık Alanları'),
        ),
    ]
