# Generated by Django 5.0.9 on 2026-03-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_about_doctor_photo_alter_doctor_specialties'),
        ('tenants', '0002_alter_clinic_options_clinic_clinic_id_clinic_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='tenants.clinic', verbose_name='Klinik'),
        ),
    ]
