# Generated by Django 5.0.9 on 2026-03-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_populate_login_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='login_code',
            field=models.CharField(blank=True, default='', help_text='Doktorun panele giriş için kullandığı 6 haneli kod', max_length=6, verbose_name='Giriş Kodu'),
        ),
        migrations.DeleteModel(
            name='DoctorLoginCode',
        ),
    ]
