# Generated by Django 5.0.9 on 2026-03-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_login_code_delete_doctorlogincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='login_otp',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Giriş OTP'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='login_otp_exp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Son Kullanma'),
        ),
    ]
